Dynamic spheres
spencerdearman/divemeets-app pull request #206
Opened 2023-07-16 04:55 UTC by spencerdearman

<img width="878" alt="Screenshot 2023-07-15 at 10 26 06 PM" src="https://github.com/spencerdearman/divemeets-app/assets/121642493/1dfff66f-9ce8-46b5-a18f-a5b46da7fc7d">

2023-07-16 04:56 UTC, spencerdearman commented
<img width="886" alt="Screenshot 2023-07-15 at 10 26 15 PM" src="https://github.com/spencerdearman/divemeets-app/assets/121642493/1ffd458c-da2c-4d7d-a7ba-8c55ff3b9130">
<img width="873" alt="Screenshot 2023-07-15 at 10 26 21 PM" src="https://github.com/spencerdearman/divemeets-app/assets/121642493/f98d9ba6-c699-451c-9dce-83d71e2e4f92">
<img width="617" alt="Screenshot 2023-07-15 at 10 25 15 PM" src="https://github.com/spencerdearman/divemeets-app/assets/121642493/2a133143-bb71-4da2-b3e3-b03a73fe2c02">
<img width="619" alt="Screenshot 2023-07-15 at 10 25 25 PM" src="https://github.com/spencerdearman/divemeets-app/assets/121642493/bca8127a-c446-43a0-8bb3-a699862ba3fe">
<img width="873" alt="Screenshot 2023-07-15 at 10 25 41 PM" src="https://github.com/spencerdearman/divemeets-app/assets/121642493/55c4a286-2929-4092-ab20-71e22c4e628e">
<img width="616" alt="Screenshot 2023-07-15 at 10 25 57 PM" src="https://github.com/spencerdearman/divemeets-app/assets/121642493/e05912da-13dc-4ad0-a14b-ee6a7b67fe34">

2023-07-16 21:19 UTC, lsherwin10 commented
What are your thoughts on the stroke of the background lines and circles? Personally think they might be a little thick on the iPad views but what do you think

2023-07-16 21:28 UTC, lsherwin10 requested changes
I added a comment about the stroke width also in the PR, interested to hear your thoughts

2023-07-16 21:28 UTC, lsherwin10 commented on DiveMeets/DiveMeets/Views/Home/Home.swift
> +    private var screenHeight = UIScreen.main.bounds.height
```suggestion
    private let screenWidth = UIScreen.main.bounds.width
    private let screenHeight = UIScreen.main.bounds.height
```
We should use let instead here since we don't want those values to be modifiable.

2023-07-16 21:28 UTC, lsherwin10 commented on DiveMeets/DiveMeets/Views/LiveResults/LiveResultsView.swift
> +    private var screenHeight = UIScreen.main.bounds.height
```suggestion
    private let screenWidth = UIScreen.main.bounds.width
    private let screenHeight = UIScreen.main.bounds.height
```

2023-07-16 21:28 UTC, lsherwin10 commented on DiveMeets/DiveMeets/Views/Login/LoginScreen.swift
> +    var screenHeight = UIScreen.main.bounds.height
```suggestion
    private let screenWidth = UIScreen.main.bounds.width
    private let screenHeight = UIScreen.main.bounds.height
```

2023-07-16 21:28 UTC, lsherwin10 commented on DiveMeets/DiveMeets/Views/Login/LoginScreen.swift
> +                    -UIScreen.main.bounds.width / 2 // Align the text to the leading edge of the screen
```suggestion
                    -screenWidth / 2 // Align the text to the leading edge of the screen
```

2023-07-16 21:28 UTC, lsherwin10 commented on DiveMeets/DiveMeets/Views/Main/ContentView.swift
> +    @State private var selectedTab: Tab = .magnifyingglass
```suggestion
    @State private var selectedTab: Tab = .house
```

2023-07-16 21:28 UTC, lsherwin10 commented on DiveMeets/DiveMeets/Views/Main/ContentView.swift
> +                                            LiveResultsView(request: "debug")
```suggestion
                                        //NavigationView {
                                            //LiveResultsView(request: "debug")
```

2023-07-16 21:28 UTC, lsherwin10 commented on DiveMeets/DiveMeets/Views/Main/ContentView.swift
> +//                                        ToolsMenu()
```suggestion
                                        //}
                                        //.navigationViewStyle(StackNavigationViewStyle())
                                        ToolsMenu()
```

2023-07-16 21:28 UTC, lsherwin10 commented on DiveMeets/DiveMeets/Views/Search/SearchView.swift
> +
```suggestion
```
I didn't see these used anywhere in the struct

2023-07-16 21:28 UTC, lsherwin10 commented on DiveMeets/DiveMeets/Views/Search/SearchView.swift
> +    }
```suggestion
```
I don't think this is used

2023-07-16 21:30 UTC, lsherwin10 commented
Also how do you feel about having a bubble behind the "Live Rankings" text on the Live Results view? I think it would make it a little easier to see and read when around the backgorund circles

2023-07-17 15:43 UTC, spencerdearman commented
Made changes, going to merge manually into new project

2023-07-17 15:52 UTC, spencerdearman commented
Manually Merged

2023-07-17 15:52 UTC, closed without merging